#version 460

#extension GL_EXT_scalar_block_layout : enable

#include "definitions.glsl"

layout(binding = 0, set = UPDATE_PER_FRAME) uniform TCullingData {
    vec4 frustumPlanes[6];
    uint maxDrawCount;
};

layout(binding = 1, set = UPDATE_PER_FRAME, std430) buffer readonly InIndirectCommands {
	VkDrawIndexedIndirectCommand inDrawCommands[];
};

layout(binding = 2, set = UPDATE_PER_FRAME, std430) buffer writeonly OutIndirectCommands {
	VkDrawIndexedIndirectCommand outDrawCommands[];
};

layout(binding = 3, set = UPDATE_PER_FRAME, std430) buffer writeonly OutDrawData {
	uint outDrawData[];
};

layout(binding = 4, set = UPDATE_PER_FRAME, std430) buffer DrawCallCount {
	uint outIndirectDrawCount;
};

layout(local_size_x = 64) in;

void main() {
    uint drawID = gl_GlobalInvocationID.x;
    if (drawID < maxDrawCount) {
        VkDrawIndexedIndirectCommand drawCommand = inDrawCommands[drawID];
        if (drawCommand.instanceCount > 0) {
            uint compactedIndex = atomicAdd(outIndirectDrawCount, 1);
            outDrawCommands[compactedIndex] = drawCommand;
            outDrawData[compactedIndex] = drawID;
        }
    }
}
