#version 460

#extension GL_EXT_scalar_block_layout : enable

#include "definitions.glsl"

layout(binding = 0, set = UPDATE_PER_FRAME, scalar) uniform TCullingData {
    uint ortho;
    vec3 viewDirectionOrCameraPos;
    vec4 frustumPlanes[6];
    uint globalDrawOffset;
    uint maxDrawCount;
} uCullingData;
layout(binding = 1, set = UPDATE_PER_FRAME, scalar) readonly buffer TMeshData {
    MeshData uMeshData[];
};
layout(binding = 2, set = UPDATE_PER_FRAME) buffer writeonly CommandBuffer {
	VkDrawIndexedIndirectCommand uOutCommands[];
};
layout(binding = 3, set = UPDATE_PER_FRAME, std430) buffer DrawCallCount {
	uint uOutIndirectDrawCount;
};
layout(binding = 4, set = UPDATE_PER_FRAME, std430) buffer writeonly OutDrawData {
	uint uOutPerDraw[];
};

layout(binding = 0, set = UPDATE_ONCE, scalar) readonly buffer TSceneData {
    DrawData uPersistentSceneData[];
};

layout(local_size_x = 64) in;

bool TestAABB(mat4 model, const vec3 min, const vec3 max) {
    vec3 boxPoints[8] = vec3[](
        vec3(min.x, min.y, min.z),
        vec3(max.x, min.y, min.z),
        vec3(max.x, max.y, min.z),
        vec3(min.x, max.y, min.z),
        vec3(min.x, min.y, max.z),
        vec3(max.x, min.y, max.z),
        vec3(max.x, max.y, max.z),
        vec3(min.x, max.y, max.z)
    );

    for (uint cornerIndex = 0; cornerIndex < 8; ++cornerIndex) {
        boxPoints[cornerIndex] = vec3(model * vec4(boxPoints[cornerIndex], 1.0f));
    }

    for (uint planeIndex = 0; planeIndex < 6; ++planeIndex) {
        bool intersects = false;
        vec4 plane = uCullingData.frustumPlanes[planeIndex];
        for (uint cornerIndex = 0; cornerIndex < 8; ++cornerIndex) {
            if (dot(vec4(boxPoints[cornerIndex], 1.0f), plane) > 0) {
                intersects = true;
                break;
            }
        }
        if (!intersects) {
            return false;
        }
    }
    return true;
}

bool TestCone(mat3 normal, mat4 model, vec3 coneDir, vec3 coneApex, float coneCutoff) {
    vec3 axis = normalize(normal * coneDir);
    vec3 apex = vec3(model * vec4(coneApex, 1.0)).xyz;
    vec3 view = uCullingData.ortho == 0 ? normalize(apex - uCullingData.viewDirectionOrCameraPos) : uCullingData.viewDirectionOrCameraPos;
    return dot(view, axis) < coneCutoff;
}

void main() {
    uint localDrawID = gl_GlobalInvocationID.x;
    if (localDrawID < uCullingData.maxDrawCount) {
        uint globalDrawID = uCullingData.globalDrawOffset + localDrawID;
        const DrawData perDrawData = uPersistentSceneData[globalDrawID];
        const MeshData perMeshData = uMeshData[perDrawData.meshIndex];

        const mat4 modelMatrix = perMeshData.modelMatrix;
        const mat3 normalTransform = perMeshData.normalTransform;

        bool isVisible = TestAABB(modelMatrix, perDrawData.minBounds, perDrawData.maxBounds)
            && TestCone(normalTransform, modelMatrix, perDrawData.coneAxis, perDrawData.coneApex, perDrawData.coneCutoff);

        VkDrawIndexedIndirectCommand command;
        command.indexCount = perDrawData.indexCount;
        command.instanceCount = isVisible ? 1 : 0;
        command.firstIndex = perDrawData.firstIndex;
        command.vertexOffset = perDrawData.vertexOffset;
        command.firstInstance = 0;

        if (isVisible) {
            uint compactedIndex = atomicAdd(uOutIndirectDrawCount, 1);
            uOutPerDraw[compactedIndex] = globalDrawID;
            uOutCommands[compactedIndex] = command;
        }
    }

}
