#version 460
#extension GL_EXT_ray_tracing : enable
#extension GL_EXT_nonuniform_qualifier : enable

#include "definitions.glsl"
#include "ddgiUtils.glsl"
#include "glossyReflectionsParameters.glsl"
#include "visibilityBufferUtils.glsl"
#include "shading.glsl"
#include "utils.glsl"

layout(location = ColorPayloadIndex) rayPayloadEXT RayPayload rayPayload;

vec4 sampleTexture(int index, InterpolatedWithDerivsVec2 uv) {
    return textureGrad(
            sampler2D(uSceneTextures[nonuniformEXT(index)], uMaterialTextureSampler),
            uv.value,
            uv.ddx,
            uv.ddy);
}

void main() {
    ivec2 vbSize = textureSize(usampler2D(uVisibilityBuffer, uFrameBufferTextureSampler), 0);
    vec2 inTexCoord = (vec2(gl_LaunchIDEXT.xy) + vec2(0.5f)) / vec2(vbSize);
    uint encodedVbData = texelFetch(
            usampler2D(uVisibilityBuffer, uFrameBufferTextureSampler),
            ivec2(inTexCoord * vbSize),
            0).x;

    vec2 ndc = inTexCoord * 2.0 - 1.0;

    if (encodedVbData == PRIMITIVE_ID_NONE) {
        ProceduralSkyShaderParameters params = initSkyShaderParameters(-uLightParameters.direction);
        params.lightColor = normalize(uLightParameters.radiance);
        vec3 viewDir = viewDirFromViewProjection(uCameraParameters.invViewProjection, ndc);
        imageStore(uReflectionTarget, ivec2(gl_LaunchIDEXT.xy), vec4(getProceduralSkyColor(params, viewDir, 0), 0.0));
        return;
    }

    uvec2 decodedVertexData = decodeVBData(encodedVbData);

    uint drawId = decodedVertexData.x;
    const DrawData drawData = uPersistentSceneData[drawId];
    const MeshData meshData = uMeshData[drawData.meshIndex];

    uint triangleIndex = decodedVertexData.y * 3 + drawData.firstIndex;

    uint vertexIndexA = uIndices[triangleIndex] + drawData.vertexOffset;
    uint vertexIndexB = uIndices[triangleIndex + 1] + drawData.vertexOffset;
    uint vertexIndexC = uIndices[triangleIndex + 2] + drawData.vertexOffset;

    vec3 posA = uPositions[vertexIndexA];
    vec3 posB = uPositions[vertexIndexB];
    vec3 posC = uPositions[vertexIndexC];

    posA = (meshData.modelMatrix * vec4(posA, 1.0)).xyz;
    posB = (meshData.modelMatrix * vec4(posB, 1.0)).xyz;
    posC = (meshData.modelMatrix * vec4(posC, 1.0)).xyz;

    BarycentricDeriv bary = CalcFullBary(
        uCameraParameters.viewProjection * vec4(posA, 1.0),
        uCameraParameters.viewProjection * vec4(posB, 1.0),
        uCameraParameters.viewProjection * vec4(posC, 1.0),
        ndc,
        vbSize
    );

    vec3 worldPos = interpolate(bary, posA, posB, posC);

    vec2 texCoordA = unpackHalf2x16(uPackedTexCoord[vertexIndexA]);
    vec2 texCoordB = unpackHalf2x16(uPackedTexCoord[vertexIndexB]);
    vec2 texCoordC = unpackHalf2x16(uPackedTexCoord[vertexIndexC]);
    InterpolatedWithDerivsVec2 uvWithDerivs = interpolateWithDerivs(
        bary,
        texCoordA,
        texCoordB,
        texCoordC
    );
    vec2 uv = uvWithDerivs.value;

    vec3 unpackedNormalA = normalize(unpackSnorm4x8(uPackedNormal[vertexIndexA]).xyz);
    vec3 unpackedNormalB = normalize(unpackSnorm4x8(uPackedNormal[vertexIndexB]).xyz);
    vec3 unpackedNormalC = normalize(unpackSnorm4x8(uPackedNormal[vertexIndexC]).xyz);

    vec3 normal = normalize(meshData.normalTransform * interpolate(bary, unpackedNormalA, unpackedNormalB, unpackedNormalC));
    
    vec4 unpackedTangentA = unpackSnorm4x8(uPackedTangent[vertexIndexA]);
    vec4 unpackedTangentB = unpackSnorm4x8(uPackedTangent[vertexIndexB]);
    vec4 unpackedTangentC = unpackSnorm4x8(uPackedTangent[vertexIndexC]);

    vec4 tangent = interpolate(bary, unpackedTangentA, unpackedTangentB, unpackedTangentC);
    vec3 normalizedTangent = normalize(meshData.normalTransform * tangent.xyz);
    vec3 bitangent = normalize(cross(normal, normalizedTangent) * tangent.w);

    mat3 TBN = mat3(normalizedTangent, bitangent, normal);

    uint materialId = meshData.materialId;
    Material material = uMaterials[materialId];

    if (material.normalTextureIndex >= 0) {
        vec3 normalSample = sampleTexture(material.normalTextureIndex, uvWithDerivs).xyz;
        vec3 normalTangentSpace = normalize(normalSample * 2.0 - 1.0);
        normal = normalize(TBN * normalTangentSpace);
    }

    float roughness = material.roughness;
    float metallic = material.metallic;
    if (material.metallicRoughnessTextureIndex >= 0) {
        vec2 metallicRoughness = sampleTexture(material.metallicRoughnessTextureIndex, uvWithDerivs).rg;
        roughness = metallicRoughness.r;
        metallic = metallicRoughness.g;
    }

    vec4 albedo = vec4(material.albedo.rgb, 0.5f);
    if (material.albedoTextureIndex >= 0) {
        albedo = sampleTexture(material.albedoTextureIndex, uvWithDerivs);
    }

    vec3 V = normalize(uCameraParameters.cameraPos.xyz - worldPos);

    vec3 origin = worldPos + normal * 1e-3;
    vec3 direction = reflect(-V, normal);

    rayPayload.color = vec3(0.0f);
    rayPayload.depth = 0;

    traceRayEXT(
        uTopLevelAS,
        gl_RayFlagsOpaqueEXT,
        AllMask,
        DefaultSBTOffset,
        DefaultSBTStride,
        ColorMissIndex,
        origin,
        0.01,
        direction,
        1000.0f,
        ColorPayloadIndex);

    vec3 reflectionColor = rayPayload.color;

    imageStore(uReflectionTarget, ivec2(gl_LaunchIDEXT.xy), vec4(reflectionColor, 0.0));
}
