#version 460
#extension GL_EXT_ray_tracing : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_GOOGLE_include_directive : enable

#include "definitions.glsl"

layout(binding = 0, set = UPDATE_PER_FRAME, scalar) uniform TCameraParameters {
    CameraData CameraParameters;
};

layout(binding = 0, set = UPDATE_ONCE) uniform accelerationStructureEXT topLevelAS;
layout(binding = 1, set = UPDATE_ONCE, rgba8) uniform image2D image;

layout(location = ColorPayloadIndex) rayPayloadEXT RayPayload rayPayload;

void main() {
    const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);
    const vec2 inUV = pixelCenter / vec2(gl_LaunchSizeEXT.xy);
    vec2 d = inUV * 2.0 - 1.0;

    vec3 origin = (CameraParameters.invView * vec4(0, 0, 0, 1)).xyz;
    vec4 target = CameraParameters.invProjection * vec4(d.x, d.y, 1, 1);
    vec3 direction = (CameraParameters.invView * vec4(normalize(target.xyz), 0)).xyz;

    rayPayload.color = vec3(0.0f);
    rayPayload.depth = 0;

    traceRayEXT(
        topLevelAS,
        gl_RayFlagsOpaqueEXT,
        AllMask,
        DefaultSBTOffset,
        DefaultSBTStride,
        ColorMissIndex,
        origin,
        TMin,
        direction,
        TMax,
        ColorPayloadIndex);

    imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(rayPayload.color, 0.0));
}
