#version 460
#extension GL_EXT_ray_tracing : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_GOOGLE_include_directive : enable

#include "definitions.glsl"

layout(binding = 0, set = UPDATE_PER_FRAME, scalar) uniform TCameraParameters {
    CameraData uCameraParameters;
};
layout(binding = 1, set = UPDATE_PER_FRAME, scalar) uniform TLightParameters {
    LightData uLightParameters;
};
layout(binding = 2, set = UPDATE_PER_FRAME, scalar) readonly buffer TMeshData {
    MeshData uMeshData[];
};

layout(binding = 0, set = UPDATE_ONCE, scalar) readonly buffer TSceneData {
    DrawData uPersistentSceneData[];
};
layout(binding = 1, set = UPDATE_ONCE) uniform accelerationStructureEXT uTopLevelAS;
layout(binding = 2, set = UPDATE_ONCE, rgba8) uniform image2D uImage;
layout(binding = 3, set = UPDATE_ONCE) uniform sampler uMaterialTextureSampler;
layout(binding = 4, set = UPDATE_ONCE) uniform sampler uFrameBufferTextureSampler;
layout(binding = 5, set = UPDATE_ONCE, scalar) readonly buffer TMaterial {
    Material uMaterials[];
};
layout(binding = 6, set = UPDATE_ONCE, scalar) readonly buffer Index {
    uint uIndices[];
};
layout(binding = 7, set = UPDATE_ONCE, scalar) readonly buffer VertexPosition {
    vec3 uPositions[];
};
layout(binding = 8, set = UPDATE_ONCE, scalar) readonly buffer PackedTexCoord {
    uint uPackedTexCoord[];
};
layout(binding = 9, set = UPDATE_ONCE, scalar) readonly buffer PackedNormal {
    uint uPackedNormal[];
};
layout(binding = 10, set = UPDATE_ONCE, scalar) readonly buffer PackedTangent {
    uint uPackedTangent[];
};
layout(binding = 11, set = UPDATE_ONCE) uniform texture2D uSceneTextures[];

layout(location = ColorPayloadIndex) rayPayloadEXT RayPayload rayPayload;

void main() {
    const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);
    const vec2 inUV = pixelCenter / vec2(gl_LaunchSizeEXT.xy);
    vec2 d = inUV * 2.0 - 1.0;

    vec3 origin = (uCameraParameters.invView * vec4(0, 0, 0, 1)).xyz;
    vec4 target = uCameraParameters.invProjection * vec4(d.x, d.y, 1, 1);
    vec3 direction = (uCameraParameters.invView * vec4(normalize(target.xyz), 0)).xyz;

    rayPayload.color = vec3(0.0f);
    rayPayload.depth = 0;

    traceRayEXT(
        uTopLevelAS,
        gl_RayFlagsOpaqueEXT,
        AllMask,
        DefaultSBTOffset,
        DefaultSBTStride,
        ColorMissIndex,
        origin,
        TMin,
        direction,
        TMax,
        ColorPayloadIndex);

    imageStore(uImage, ivec2(gl_LaunchIDEXT.xy), vec4(rayPayload.color, 0.0));
}
