#version 460

#extension GL_EXT_scalar_block_layout : enable

#include "definitions.glsl"
#include "ddgiUtils.glsl"
#include "updateProbesParameters.glsl"

#define LOCAL_SIZE_X 8
#define LOCAL_SIZE_Y 8
#define CACHE_SIZE 64

layout(local_size_x = LOCAL_SIZE_X, local_size_y = LOCAL_SIZE_Y) in;

shared vec4 RayDirectionDepthCache[CACHE_SIZE];
shared vec3 RayRadianceCache[CACHE_SIZE];

vec3 sampleProbeIrradiance(uvec3 coordinates) {
    return texelFetch(sampler2DArray(uPrevIrradianceTargets, uFramebufferSampler), ivec3(coordinates), 0).rgb;
}

vec2 sampleProbeMoments(uvec3 coordinates) {
    return texelFetch(sampler2DArray(uPrevProbeMoments, uFramebufferSampler), ivec3(coordinates), 0).rg;
}

vec4 sampleDirectionDepth(ivec2 coodinates) {
    return texelFetch(
        sampler2D(uProbeDirectionDepth, uFramebufferSampler),
        coodinates,
        0);
}

vec3 sampleRadiance(ivec2 coordinate) {        
    return texelFetch(
            sampler2D(uProbeRadianceTargets, uFramebufferSampler),
            coordinate,
            0).xyz;
}

// Caching idea from: https://github.com/diharaw/hybrid-rendering/blob/master/src/shaders/gi/gi_probe_update.glsl
void populateCache(uint probeId, uint offset, uint batchRays, uint totalRays) {
    const uint localRayIndex = uint(gl_LocalInvocationIndex);
    if (localRayIndex < batchRays) {
        const uint rayIndex = localRayIndex + offset;
        vec4 directionDepth = sampleDirectionDepth(ivec2(rayIndex, probeId));
        const vec3 direction = normalize(directionDepth.xyz);
        const float depth = directionDepth.w;
        RayDirectionDepthCache[localRayIndex] = vec4(direction, depth);
        RayRadianceCache[localRayIndex] = sampleRadiance(ivec2(rayIndex, probeId));
    }
}

void main() {
    const uint probeIndex = gl_GlobalInvocationID.z;

    const vec2 pixelCenter = vec2(gl_GlobalInvocationID.xy) + vec2(0.5);
    const vec2 uv = pixelCenter / vec2(gl_NumWorkGroups.xy * gl_WorkGroupSize.xy);

    const vec3 texelDirection = octDecode(uv);

    ivec2 firstStageSize = textureSize(sampler2D(uProbeRadianceTargets, uFramebufferSampler), 0);
    const uint raysPerProbe = uint(firstStageSize.x);

    const uint raysPerBatch = CACHE_SIZE;

    float sumWeight = 0.0f;
    vec2 moments = vec2(0.0f);
    vec3 irradiance = vec3(0.0f);
    for (uint rayIndex = 0; rayIndex < raysPerProbe; rayIndex += raysPerBatch) {
        populateCache(probeIndex, rayIndex, raysPerBatch, raysPerProbe);

        barrier();

        for (uint cachedRayIndex = 0; cachedRayIndex < raysPerBatch; ++cachedRayIndex) {
            vec4 rayDirectionDepth = RayDirectionDepthCache[cachedRayIndex];
            const vec3 direction = rayDirectionDepth.xyz;
            const float depth = rayDirectionDepth.w;

            vec3 radiance = RayRadianceCache[cachedRayIndex];

            float weight = max(0.0, dot(texelDirection, direction));

            irradiance += weight * radiance * uDDGI.energyPreservation;
            moments.x += weight * depth;
            moments.y += weight * depth * depth;
            sumWeight += weight;
        }

        barrier();
    }

    vec3 prevFrameIrradiance = uDDGI.frameIndex == 0 ? vec3(0.0f) : sampleProbeIrradiance(gl_GlobalInvocationID);
    vec2 prevFrameMoments = uDDGI.frameIndex == 0 ? vec2(0.0f) : sampleProbeMoments(gl_GlobalInvocationID);
    float hysteresis = uDDGI.frameIndex == 0 ? 0.0f : uDDGI.hysteresis;

    if (sumWeight >= 1e-6) {
        irradiance /= sumWeight;
        moments /= sumWeight;
        irradiance = mix(irradiance, prevFrameIrradiance, hysteresis);
        moments = mix(moments, prevFrameMoments, hysteresis);
    } else {
        irradiance = prevFrameIrradiance;
        moments = prevFrameMoments;
    }

    imageStore(uConvolutedProbeIrradianceTargets, ivec3(gl_GlobalInvocationID), vec4(irradiance, 0.0));
    imageStore(uProbeMoments, ivec3(gl_GlobalInvocationID), vec4(moments, 0.0, 0.0));
}
