#version 460

#extension GL_EXT_scalar_block_layout : enable

#include "definitions.glsl"
#include "ddgiUtils.glsl"
#include "updateProbesParameters.glsl"

layout(local_size_x = 8, local_size_y = 8) in;

vec3 sampleProbeIrradiance(uvec3 coordinates) {
    return texelFetch(sampler2DArray(uPrevIrradianceTargets, uFramebufferSampler), ivec3(coordinates), 0).rgb;
}

vec2 sampleProbeMoments(uvec3 coordinates) {
    return texelFetch(sampler2DArray(uPrevProbeMoments, uFramebufferSampler), ivec3(coordinates), 0).rg;
}

void main() {
    const uint probeIndex = gl_GlobalInvocationID.z;

    const vec2 pixelCenter = vec2(gl_GlobalInvocationID.xy) + vec2(0.5);
    const vec2 uv = pixelCenter / vec2(gl_NumWorkGroups.xy * gl_WorkGroupSize.xy);

    const vec3 texelDirection = octDecode(uv);

    ivec2 firstStageSize = textureSize(sampler2D(uProbeRadianceTargets, uFramebufferSampler), 0);
    const uint raysPerProbe = uint(firstStageSize.x);

    const float energyConservation = 0.95f;

    float sumWeight = 0.0f;
    vec2 moments = vec2(0.0f);
    vec3 irradiance = vec3(0.0f);
    for (uint rayIndex = 0; rayIndex < raysPerProbe; ++rayIndex) {
        ivec2 sampleIndex = ivec2(int(rayIndex), int(probeIndex));

        const vec4 directionDepth = texelFetch(
            sampler2D(uProbeDirectionDepth, uFramebufferSampler),
            sampleIndex,
            0);
        const vec3 direction = normalize(directionDepth.xyz);
        const float depth = directionDepth.w;

        const vec3 radiance = energyConservation * texelFetch(
            sampler2D(uProbeRadianceTargets, uFramebufferSampler),
            sampleIndex,
            0).xyz;
        
        float weight = max(0.0, dot(texelDirection, direction));

        irradiance += weight * radiance;
        moments.x += weight * depth;
        moments.y += weight * depth * depth;

        sumWeight += weight;
    }

    if (sumWeight < 1e-6) {
        irradiance = vec3(0.0f);
        moments = vec2(INF);
    } else {
        irradiance /= sumWeight;
        moments /= sumWeight;
    }

    vec3 prevFrameIrradiance = uDDGI.frameIndex == 0 ? vec3(0.0f) : sampleProbeIrradiance(gl_GlobalInvocationID);
    vec2 prevFrameMoments = uDDGI.frameIndex == 0 ? vec2(0.0f) : sampleProbeMoments(gl_GlobalInvocationID);

    irradiance = mix(prevFrameIrradiance, irradiance, uDDGI.hysteresis);
    moments = mix(prevFrameMoments, moments, uDDGI.hysteresis);

    imageStore(uConvolutedProbeIrradianceTargets, ivec3(gl_GlobalInvocationID), vec4(irradiance, 0.0));
    imageStore(uProbeMoments, ivec3(gl_GlobalInvocationID), vec4(moments, 0.0, 0.0));
}
